sweep_config = {
    'pretrained_path': None, 
    'retake_training': False,
    'dim_feedforward': 1024,
    'nheads': 16,
    'masking_p': 0.15,
    'nlayers': 12,
    'dropout': 0.0,
    'dim_model': 512,
    'batch_first': True,
    'n_tokens': 20340, 
    'batch_size': 6,
    'context_length': 1500,
    'lr': 7e-4,
    'warmup': 100000, 
    'max_epochs': 30661140, 
    'autoregressive': False,
    'pool': None,
    'supervised_task': False,
    'learnable_pe': True,
    'organ': "everything",
    'specie': True,
    'assay': True,
    'modality': True,
    }
